version: '3'
services:
  cloud-frontend:
    build:
      context: .
    command: sh -c "npm run build && npm start"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    container_name: cloud-frontend
