# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x0b\x64\x61taservice\"7\n\x17GetAIPredictionsRequest\x12\x1c\n\x14\x63urrent_weather_json\x18\x01 \x01(\t\"7\n\x18GetAIPredictionsResponse\x12\x1b\n\x13\x61i_predictions_json\x18\x01 \x01(\t2r\n\x0b\x44\x61taService\x12\x63\n\x14GetAIPredictionsData\x12$.dataservice.GetAIPredictionsRequest\x1a%.dataservice.GetAIPredictionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETAIPREDICTIONSREQUEST']._serialized_start=27
  _globals['_GETAIPREDICTIONSREQUEST']._serialized_end=82
  _globals['_GETAIPREDICTIONSRESPONSE']._serialized_start=84
  _globals['_GETAIPREDICTIONSRESPONSE']._serialized_end=139
  _globals['_DATASERVICE']._serialized_start=141
  _globals['_DATASERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
