version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
      - '50051:50051'
    volumes:
      - .:/app
    command: ['python', 'app.py']
