version: '3'

services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka-broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_NODE_ID: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    networks:
      - kafka_network

  fastify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastify-app
    ports:
      - '3000:3000' # Expose Fastify app on port 3000
    depends_on:
      - kafka # Ensure Kafka starts before Fastify
    networks:
      - kafka_network
    environment:
      KAFKA_BROKER: kafka-broker:9092 # Set Kafka broker address
    volumes:
      - .:/app # Mount the local directory for live reload

networks:
  kafka_network:
    driver: bridge
