apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: pot4t0/cloud15:ai
          resources:
            requests:
              cpu: 500m
            limits:
              cpu: 1000m

---
apiVersion: v1
kind: Service
metadata:
  name: ai
  labels:
    app: ai
spec:
  type: ClusterIP # Change to NodePort if you need external access
  ports:
    - port: 50051 # Port for the service
      targetPort: 50051 # Port where the application listens
  selector:
    app: ai # This matches the deployment labels
