version: '3'
services:
  my-react-app:
    image: my-react-app-image
    container_name: cloudproject-frontend
    ports:
      - "3000:3000"
    build:
      context: .
    command: ["npm", "start"]
